### ISSUE TITLE
Process takes too long - how to filter PAF

### ISSUE THREAD

**Issue by ms-gx** [morispi/LoRSCo#10]
The whole process takes too long with my data. At least for a first try.

What I would do is to filter the PAF file for column 7 (target length, > 20'000bp) and then to process the next steps manually/modifying the script.

Is it correct to filter PAF according to target length? I guess this way I will only polish the reads above my threshold of 20'000. Is this in accordance with the downstream processing? I guess the reads which have no hits in the PAF (as target) will just get dropped?

**Comment by natir** [comment]
I can answer the question of how to filter on size of the query:

```
{minimap command} | awk '$7 >= {your size threshold}' > file_contains_only_query_upper_than_20000.paf
```

$7 is for column seven, $2 is for column second.

For other question I don't know sorry.

Edit:

You need filter your file before indexed with fpa.

**Comment by morispi** [comment]
Hi,

There should be no problem only correcting reads longer than a given threshold, this won't affecter the downstream processing. Reads with no hit in the PAF file indeed just get dropped.

You'll just have to run Minimap, filter the mappings you don't want to keep, and then index the PAF file with fpa.
You should be able to do it directly with pipes, probably something like:

`minimap [params] | filter [params] | fpa [params]`

Reusing the minimap and fpa commands / parameters used in CONSENT, and the filter command natir provided.

However, you should filter according to the query length, and not to the target. So use '$2' instead of '$7'.

Cheers
P

**Comment by ms-gx** [comment]
Thanks to you both. I did it in the meantime as you said. It worked. And yes, obviously it is $2 :)
