### ISSUE TITLE
fpa

### ISSUE THREAD

**Issue by linslsf** [morispi/LoRSCo#11]
Hi I am trying to run CONSENT-correct buy I run in the following error:

${consent} --in ${input_directory} --out ${output}/test_consent.fasta --type ONT

Self-aligning the long reads (minimap2)
[ERROR] failed to open file 'i-k15'
error: Found argument '-' which wasn't expected, or isn't valid in this context

USAGE:
    fpa [OPTIONS] [SUBCOMMAND]

For more information try --help

**Comment by linslsf** [comment]
I am using fpa version 0.5

**Comment by francesco-peverelli** [comment]
I had the same issue. I eliminated the '-' and added a -o before the next argument in the fpa command in CONSENT-correct.sh and it seems to be working fine that way.

**Comment by drk0311** [comment]
I also got an error like
"error: Found argument '-' which wasn't expected, or isn't valid in this context"
in the very first step. 

Was fixed by correcting "| fpa - $tmpdir/"$alignments"" to "| fpa -o $tmpdir/"$alignments"" in line 175 and 177 of CONSENT-correct file.

Think this is a good error-correction tool so hope the fixed verion will be released.

**Comment by morispi** [comment]
Hi everyone,

Sorry for the long delay in answering / resolving that.
Just merged a pull request resolving the issue.

Best,
Pierre
